config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :books, only: [:create, :show, :index, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # 画像
  attachment :profile_image

  # 各modelとの関連付け(アソシエーション)、所有数が一つとは限らないので複数形、destroyで関連付け削除
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships
  # source: :followにてrelationshipsテーブルのfollow_idを参考にしてfollowingsモデルにアクセス
  has_many :followings, through: :relationships, source: :follow
  # foreign_key: 'follow_id'にてfollow_idを入り口としてrelaitionshipsテーブルにアクセスする（入り口）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # source: :userで出口をuser_idにする。userテーブルから自分をフォローしているuserを取ってくる
  has_many :followers, through: :reverse_of_relationships, source: :user


  #validation使用
  validates :name, presence:true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50 }

  # userモデルにフォロー機能のメソッドを記載
  def follow(other_user)
    # フォローしようとしているother_userが自分自身ではないか検証
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

# フォローがあればアンフォローを行う
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    # self.followwingsによりフォローしているUser達を取得。include?(other_user)によりother_userが含まれていないか確認
    self.followings.include?(other_user)
  end

# ここでのself.はUser.を意味する
  def self.search(method,word)
    if method == "forward_match"
      @users = User.where("name LIKE ?","#{word}%")
    elsif method == "backward_match"
      @users = User.where("name LIKE ?","%#{word}")
    elsif method == "perfect_match"
      @users = User.where("name LIKE ?","#{word}")
    elsif method == "partial_match"
      @users = User.where("name LIKE ?","%#{word}%")
    else
      @users = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user,only:[:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    method = params[:search_method]
    word = params[:search_word]
    @users1 = User.all
    if params[:search_select] == "user_search"
    @users = User.search(method,word)
    elsif params[:search_select] =="book_search"
      @books = Book.search(method,word)
    end
    @book = Book.new
    @user = User.find(current_user.id)

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
   else
    render :edit
  end
end

private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end

def correct_user
  user = User.find(params[:id])
  if current_user != user
    redirect_to user_path(current_user.id)
  end
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
 <footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/users/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <% if  user_signed_in? %>
          <li><%= link_to " Home", user_path(current_user), class:"glyphicon glyphicon-home home" %></li>
          <li><%= link_to " Users", users_path, class:"glyphicon glyphicon-user users" %></li>
          <li><%= link_to " Books", books_path, class:"glyphicon glyphicon-book books" %></li>
          <li><%= link_to " logout", destroy_user_session_path, method: :delete,class:"glyphicon glyphicon-log-out logout",:rel => 'nofollow'%></li>
          <% else %>
          <li><%= link_to " Home", root_path, class:"glyphicon glyphicon-home home" %></li>
          <li><%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %></li>
          <li><%= link_to " Sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %></li>
           <li><%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/users/_sidebar.html.erb
<table class='table'>

      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"  %>
      <tbody><tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
</tbody></table>

<div class="row">
  <% if user == current_user %>
  <%= link_to "", edit_user_path(user.id) ,class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  <% else %>
  <%= link_to "", user_path(current_user.id) ,class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="body">

  <%= render "users/header" %>

  <div class="container">
    <h2>User info</h2>

    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation" >
      <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
      <ul>
        <%= @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :image %><br />
      <%= f.attachment_field :profile_image %>
    </div>

    <div class="field">
      <%= f.label :introduction%>
      <%= f.text_area :introduction, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Update User" %>
    </div>

    <% end %>

  </div>

  <%= render "users/footer" %>

</div>

app/views/users/index.html.erb
<div class= "body">

	<%= render "users/header" %>

	<div class= "container">
		<div class= "row">
			<div class="col-xs-3">
				<h2>User info</h2>

				<%= render 'users/sidebar', user: @user %>
				<%= render 'books/newform', book:@book %>
			</div>

			<div class ="col-xs-9">

				<!-- 検索機能 -->
				<h3>search</h3>
				<%= form_tag(users_path, method: :get ) do %>
				<%= select(@search_content, :search_select, [["user", "user_search"],["book", "book_search"]]) %>
				<%= select(@search_content, :search_method, [["前方一致", "forward_match"],["後方一致", "backward_match"],["完全一致", "perfect_match"],["部分一致", "partial_match"]]) %>
				<%= text_field(@search_content, :search_word) %>
				<%= submit_tag 'Search', name: :nil %>
				<% end %>
				<% if params[:search_select] == "user_search" %>
				<h2>Users</h2>
				<table class ="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th>followings</th>
							<th>followers</th>
							<th colspan="2"></th>
						</tr>
					</thead>

					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %></td>
						</td>
						<td><%= user.name %></td>
						<td><%= user.followings.count %></td>
						<td><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
						<td>
							<% unless current_user == user %>
							<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
							<% end %>
							<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
							<% end %>
							<% end %>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<% elsif params[:search_select] =="book_search" %>
			<h2>Books</h2>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user.id) do %>
							<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '50x50'  %></td>
							<% end %>

							<td><%= link_to book.title, book_path(book.id) %>
							</td>
							<td><%= book.body %></td>
							<% if book.favorited_by?(current_user) %>
							<td>
								<%= link_to book_favorites_path(book.id), method: :delete do %>
								<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								<%= book.favorites.count %> いいね
								<% end %>
							</td>
							<% else %>
							<td>
								<%= link_to book_favorites_path(book.id), method: :post do %>
								<i class="fa fa-heart-o" aria-hidden="true"></i>
								<%= book.favorites.count %> いいね
								<% end %>
							</td>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
				<% elsif @users1 == User.all %>
				<h2>Users</h2>
				<table class ="table">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th>followings</th>
							<th>followers</th>
							<th colspan="2"></th>
						</tr>
					</thead>

					<tbody>
						<% @users1.each do |user| %>
						<tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %></td>
						</td>
						<td><%= user.name %></td>
						<td><%= user.followings.count %></td>
						<td><%= user.followers.count %></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
						<td>
							<% unless current_user == user %>
							<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
							<% end %>
							<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
							<% end %>
							<% end %>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<% end %>
		</div>
	</div>
</div>

<%= render 'users/footer' %>
</div>

app/views/users/show.html.erb
<div class="body">

  <%= render "users/header" %>
  <div class="container">

   <p id="notice"><%= flash[:notice] %></p>


   <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>

      <%= render 'users/sidebar', user: @user %>
      <%= render 'books/newform', book:@book %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '50x50' %></td>

            <td><%= link_to book.title, book_path(book.id) %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
            <td>
              <%= link_to book_favorites_path(book.id), method: :delete do %>
              <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
              <%= book.favorites.count %> いいね
              <% end %>
            </td>
            <% else %>
            <td>
              <%= link_to book_favorites_path(book.id), method: :post do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
              <%= book.favorites.count %> いいね
              <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>

      </table>
      <h2>followings</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @user.followings.each do |user| %>
          <tr>

            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %></td>

            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <h2>followers</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @user.followers.each do |user| %>
          <tr>

            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %></td>

            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

<%= render 'users/footer' %>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>