config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :books, only: [:create, :show, :index, :edit, :update, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :edit, :update, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'

end

app/models/book.rb
class Book < ApplicationRecord

  # userモデルに従属する
	belongs_to :user

  # 各modelとの関連付け（アソシエーション）複数形
	has_many :book_comments, dependent: :destroy
	# 1件のbookに対して複数のいいねの関係
	has_many :favorites, dependent: :destroy



	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

  # validation設定
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 199 }


  def self.search(method,word)
    if method == "forward_match"
      @books = Book.where("title LIKE?","#{word}%")
    elsif method == "backward_match"
      @books = Book.where("title LIKE?","%#{word}")
    elsif method == "perfect_match"
      @books = Book.where("title LIKE?","#{word}")
    elsif method == "partial_match"
      @books = Book.where("title LIKE?","%#{word}%")
    else
      @books = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
     if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
     else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
      @book = Book.find(params[:id])
      @book_new = Book.new
      @book_comment = BookComment.new
      @user = @book.user
  end

  def index
      method = params[:search_method]
      word = params[:search_word]
      @user = current_user
      @books = Book.search(method,word)
      @book = Book.new
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  private

  def book_params
      params.require(:book).permit(:title, :body)
  end

  def correct_user
      book = Book.find(params[:id])
      if current_user.id != book.user.id
        redirect_to books_path
      end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<h2>New book</h2>
<%= form_for(book) do |f| %>

<div class="field row">
	<label for="book_title">Title</label>
	<%= f.text_field :title, class:"col-xs-12 book_title" %>
</div>

<div class="field row">
	<label for="book_opinion">Opinion</label>
	<%= f.text_area :body, class:"col-xs-12 book_body" %>
</div>

<div class="actions row">
	<%= f.submit 'Create Book', name:"commit", class:"btn btn-primary col-xs-12" %>
</div>
<% end %>

app/views/books/edit.html.erb
<div class="body">

  <%= render "users/header" %>

  <div class="container">
    <div class="col-md-6 col-md-offset-3" >
    <h1>Editing Book</h1>

    <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
    <div id="error_explanation" >
      <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
      <ul>
        <%= @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="field row">
      <label for="book_title">Title</label>
     <%= f.text_field :title, class:"col-xs-12 book_title" %>
</div>

<div class="field row">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class:"col-xs-12 book_body" %>
</div>

<div class="actions row">
  <%= f.submit 'Update Book', name:"commit", class:"btn btn-primary col-xs-12" %>
</div>

    <% end %>
  <a class= "book_id" href="/books/<%= @book.id %>">Show</a>
  |
    <a class= "back" href="/books">Back</a>
  </div>

</div>

  <%= render "users/footer" %>

</div>

app/views/books/index.html.erb
<div class="body">

  <%= render "users/header" %>

  <div class="container">


   <p id="notice"><%= flash[:notice] %></p>

   <% if @book.errors.any? %>
   <div id="error_explanation" >
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
      <%= @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>

      <%= render 'users/sidebar', user: @user %>
      <%= render 'books/newform', book:@book %>
    </div>

    <div class="col-xs-9">



      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '50x50'  %></td>
              <% end %>

              <td><%= link_to book.title, book_path(book.id) %>
              </td>
              <td><%= book.body %></td>
              <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book.id), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= book.favorites.count %> いいね
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(book.id), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= book.favorites.count %> いいね
                <% end %>
              </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>

  <%= render 'users/footer' %>

</div>

app/views/books/show.html.erb
<div class="body">

	<%= render "users/header" %>

	<div class="container">

		<p id="notice"><%= flash[:notice] %></p>

		<div class="row">
			<div class="col-xs-3">
				<h2>User info</h2>

				<%= render 'users/sidebar', user: @user %>
				<%= render 'books/newform', book:@book_new %>
			</div>

			<div class="col-xs-9">
				<h2>Book detail</h2>

				<table class="table table-hover table-inverse">

					<tbody>
						<tr>
							<td>
								<a><%= link_to user_path(@user) do %>
									<%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '50x50'  %><br>
									<%= @user.name %></a>
								</td>
								<% end %>
								<td><%= link_to @book.title %></td>
								<td><%= @book.body %></td>
								<% if @user == current_user %>
								<td>
									<a class="btn btn-success btn-sm" href="/books/<%= @book.id %>/edit">Edit</a>
								</td>
								<td>
									<a class="btn btn-danger btn-sm" rel="nofollow" data-method="delete" href="/books/<%= @book.id %>">Destroy</a>
								</td>
								<% end %>
								<% if @book.favorited_by?(current_user) %>
								<td>
									<%= link_to book_favorites_path(@book), method: :delete do %>
									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= @book.favorites.count %> いいね
									<% end %>
								</td>
								<% else %>
								<td>
									<%= link_to book_favorites_path(@book), method: :post do %>
									<i class="fa fa-heart-o" aria-hidden="true"></i>
									<%= @book.favorites.count %> いいね
									<% end %>
								</td>
								<% end %>
								<td>
									<i class="fa fa-comment-o" aria-hidden="true"></i>
									<a href="#comments"><%= @book.book_comments.count %></a>
								</td>
							</tr>
						</tbody>

					</table>
				</div>
				<div class="col-xs-9">
					<h2>Comments</h2>
					<table class="table">
						<thead>
							<tr>
								<th colspan="1"></th>
								<th>comment</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% @book.book_comments.each do |book_comment| %>
							<tr>
								<td>
									<%= link_to user_path(book_comment.user.id) do %>
									<%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg", size: '50x50' %></td>
									<% end %>
									<td><%= book_comment.comment %></td>
									<% if book_comment.user == current_user %>
									<td>
										<a class="btn btn-success btn-sm" href="/books/<%= @book.id %>/book_comments/<%= book_comment.id %>/edit">Edit</a>
									</td>
									<td>
										<a class="btn btn-danger btn-sm" rel="nofollow" data-method="delete" href="/books/<%=@book.id %>/book_comments/<%= book_comment.id %>">Destroy</a>
									</td>
									<% end %>
									<td colspan="3"></td>
									<% end %>
								</tr>


							</tbody>
						</table>

						<%= form_for [@book, @book_comment] do |f| %>

						<%= f.text_area :comment, row:'5', class: "form-control",placeholder: "コメントはここに" %>

						<div class="float-xs-right">
							<%= f.submit 'Create comment', name:"commit", class:"btn btn-primary col-xs-3" %>
						</div>
						<% end %>

					</div>

					<div class="col-xs-9 col-xs-offset-3">
						<h2>いいねusers</h2>
						<table class="table">
							<thead>
								<tr>
									<th>image</th>
									<th>name</th>
									<th colspan="3"></th>
								</tr>
							</thead>


							<tbody>
								<% @book.favorites.each do |favorite| %>
								<tr>

									<td><%= attachment_image_tag favorite.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40'  %></td>

									<td><%= favorite.user.name %></td>
									<td><%= link_to "Show", user_path(favorite.user.id) %></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</div>


					<%= render 'users/footer' %>

				</div>